# The support page (App Store support URL), per language. The error names in q1–q4
# are the app's own messages, word for word, so that people find what they saw.
# Footer labels, skip link and language menu label come from privacy.py.

S = {}

S["en"] = {
    "title": "Support · Hybrid AutoPress",
    "description": "Help with Hybrid AutoPress: contact, answers to the most common connection problems, and the subscription.",
    "nav_home": "Home", "eyebrow": "Support",
    "h1": "Support for Hybrid AutoPress",
    "lede": "Questions, problems or requests? Write to me; I answer every message myself. Many connection problems have a quick fix, listed below.",
    "contact_h": "Contact", "contact_p": "Send an e-mail, in English or German. I usually answer within two working days.",
    "include_h": "What helps me help you",
    "include_1": "Your device and system version (iPhone, iPad or Mac; iOS, iPadOS or macOS).",
    "include_2": "The app version: on the Mac under Hybrid AutoPress → About Hybrid AutoPress.",
    "include_3": "Your WordPress version and your host, and any security or SEO plugins.",
    "include_4": "The exact message the app showed, and the steps that led to it. A screenshot is welcome.",
    "faq_h": "Common problems",
    "q1_t": "“The sign-in did not reach WordPress.”",
    "q1_p": "The web server drops the sign-in before WordPress sees it; this is common with shared hosting. Add this line to the .htaccess file in your WordPress folder, then connect again:",
    "q2_t": "“Application passwords are not available on this website.”",
    "q2_p": "They need WordPress 5.6 or later and https. Security plugins such as Wordfence switch them off by default; allow them in the plugin's settings.",
    "q3_t": "“WordPress was found, but its REST API is switched off or blocked.”",
    "q3_p": "A security plugin or a server rule blocks /wp-json/. It must be reachable for signed-in users; check the plugin's REST API settings or ask your host.",
    "q4_t": "“User name or application password are wrong.”",
    "q4_p": "Use an application password (Users → Profile → Application Passwords), not your normal login password. Or choose “Sign In via Browser”, and WordPress creates one for you.",
    "q5_t": "A picture is larger than the website accepts",
    "q5_p": "Choose a smaller longest edge in the image settings (Images in the list, on the Mac ⌘,), or raise the upload limit at your host.",
    "q6_t": "Restore or manage AutoPress Pro",
    "q6_p": "Open the Pro window and choose “Restore Purchases” on a new device with the same Apple Account, or “Manage Subscription” to change or cancel it.",
    "q7_t": "Cancellation and refunds",
    "q7_p": "The subscription runs through the App Store. It can be cancelled at any time in your Apple Account settings; refunds are handled by Apple at reportaproblem.apple.com.",
    "help_p": "The app has its own help with fourteen short topics: on the Mac under Help → AutoPress Help (⌘?), on iPhone and iPad behind the question mark at the top of the list.",
    "help_link_home": "What AutoPress can do",
    "back": "Back to the home page", "foot_support": "Support",
}

S["de"] = {
    "title": "Support · Hybrid AutoPress",
    "description": "Hilfe zu Hybrid AutoPress: Kontakt, Antworten auf die häufigsten Verbindungsprobleme und zum Abo.",
    "nav_home": "Startseite", "eyebrow": "Support",
    "h1": "Support für Hybrid AutoPress",
    "lede": "Fragen, Probleme oder Wünsche? Schreib mir; ich beantworte jede Nachricht selbst. Viele Verbindungsprobleme lassen sich schnell lösen, siehe unten.",
    "contact_h": "Kontakt", "contact_p": "Schick eine E-Mail, auf Deutsch oder Englisch. Meist antworte ich innerhalb von zwei Werktagen.",
    "include_h": "Was mir beim Helfen hilft",
    "include_1": "Dein Gerät und die Systemversion (iPhone, iPad oder Mac; iOS, iPadOS oder macOS).",
    "include_2": "Die App-Version: auf dem Mac unter Hybrid AutoPress → Über Hybrid AutoPress.",
    "include_3": "Deine WordPress-Version und deinen Hosting-Anbieter, dazu Sicherheits- oder SEO-Plugins.",
    "include_4": "Die genaue Meldung der App und die Schritte davor. Ein Bildschirmfoto ist willkommen.",
    "faq_h": "Häufige Probleme",
    "q1_t": "„Die Anmeldung ist bei WordPress nicht angekommen.“",
    "q1_p": "Der Webserver verschluckt die Anmeldung, bevor WordPress sie sieht; das ist bei Shared Hosting häufig. Füge diese Zeile in die .htaccess-Datei in deinem WordPress-Ordner ein und verbinde dich erneut:",
    "q2_t": "„Anwendungspasswörter stehen auf dieser Website nicht zur Verfügung.“",
    "q2_p": "Sie brauchen WordPress 5.6 oder neuer und https. Sicherheits-Plugins wie Wordfence schalten sie standardmäßig ab; erlaube sie in den Einstellungen des Plugins.",
    "q3_t": "„WordPress wurde gefunden, aber die REST-API ist abgeschaltet oder blockiert.“",
    "q3_p": "Ein Sicherheits-Plugin oder eine Server-Regel sperrt /wp-json/. Für angemeldete Benutzer muss es erreichbar sein; prüfe die REST-API-Einstellungen des Plugins oder frag deinen Anbieter.",
    "q4_t": "„Benutzername oder Anwendungspasswort sind falsch.“",
    "q4_p": "Verwende ein Anwendungspasswort (Benutzer → Profil → Anwendungspasswörter), nicht dein normales Login-Passwort. Oder wähle „Im Browser anmelden“, dann legt WordPress eines für dich an.",
    "q5_t": "Ein Bild ist größer, als die Website annimmt",
    "q5_p": "Wähle in den Bildeinstellungen eine kleinere lange Kante (Zeile „Bilder“ in der Liste, auf dem Mac ⌘,) oder erhöhe das Upload-Limit bei deinem Anbieter.",
    "q6_t": "AutoPress Pro wiederherstellen oder verwalten",
    "q6_p": "Öffne das Pro-Fenster und wähle „Käufe wiederherstellen“ auf einem neuen Gerät mit demselben Apple-Account, oder „Abo verwalten“, um es zu ändern oder zu kündigen.",
    "q7_t": "Kündigung und Erstattung",
    "q7_p": "Das Abo läuft über den App Store. Es lässt sich jederzeit in den Einstellungen deines Apple-Accounts kündigen; Erstattungen bearbeitet Apple unter reportaproblem.apple.com.",
    "help_p": "Die App hat eine eigene Hilfe mit vierzehn kurzen Themen: auf dem Mac unter Hilfe → AutoPress-Hilfe (⌘?), auf iPhone und iPad hinter dem Fragezeichen oben in der Liste.",
    "help_link_home": "Was AutoPress kann",
    "back": "Zurück zur Startseite", "foot_support": "Support",
}

S["fr"] = {
    "title": "Assistance · Hybrid AutoPress",
    "description": "Aide pour Hybrid AutoPress : contact, réponses aux problèmes de connexion les plus fréquents et à l'abonnement.",
    "nav_home": "Accueil", "eyebrow": "Assistance",
    "h1": "Assistance pour Hybrid AutoPress",
    "lede": "Des questions, des problèmes ou des suggestions ? Écrivez-moi ; je réponds moi-même à chaque message. Beaucoup de problèmes de connexion se règlent vite, voir ci-dessous.",
    "contact_h": "Contact", "contact_p": "Envoyez un e-mail, en anglais ou en allemand. Je réponds en général sous deux jours ouvrés.",
    "include_h": "Ce qui m'aide à vous aider",
    "include_1": "Votre appareil et la version du système (iPhone, iPad ou Mac ; iOS, iPadOS ou macOS).",
    "include_2": "La version de l'app : sur Mac, sous Hybrid AutoPress → À propos de Hybrid AutoPress.",
    "include_3": "Votre version de WordPress et votre hébergeur, ainsi que les extensions de sécurité ou SEO.",
    "include_4": "Le message exact affiché par l'app et les étapes qui y ont mené. Une capture d'écran est la bienvenue.",
    "faq_h": "Problèmes fréquents",
    "q1_t": "« L'authentification n'est pas parvenue à WordPress. »",
    "q1_p": "Le serveur web perd l'authentification avant que WordPress ne la voie ; c'est fréquent en hébergement mutualisé. Ajoutez cette ligne au fichier .htaccess de votre dossier WordPress, puis reconnectez-vous :",
    "q2_t": "« Les mots de passe d'application ne sont pas disponibles sur ce site. »",
    "q2_p": "Ils nécessitent WordPress 5.6 ou plus et https. Des extensions de sécurité comme Wordfence les désactivent par défaut ; autorisez-les dans les réglages de l'extension.",
    "q3_t": "« WordPress a été trouvé, mais son API REST est désactivée ou bloquée. »",
    "q3_p": "Une extension de sécurité ou une règle du serveur bloque /wp-json/. Il doit être accessible aux utilisateurs connectés ; vérifiez les réglages REST API de l'extension ou demandez à votre hébergeur.",
    "q4_t": "« L'identifiant ou le mot de passe d'application est incorrect. »",
    "q4_p": "Utilisez un mot de passe d'application (Utilisateurs → Profil → Mots de passe d'application), pas votre mot de passe habituel. Ou choisissez la connexion via le navigateur : WordPress en crée un pour vous.",
    "q5_t": "Une image dépasse la taille acceptée par le site",
    "q5_p": "Choisissez un grand côté plus petit dans les réglages d'images (ligne Images de la liste, sur Mac ⌘,) ou augmentez la limite d'envoi chez votre hébergeur.",
    "q6_t": "Restaurer ou gérer AutoPress Pro",
    "q6_p": "Ouvrez la fenêtre Pro et choisissez « Restaurer les achats » sur un nouvel appareil avec le même compte Apple, ou « Gérer l'abonnement » pour le modifier ou le résilier.",
    "q7_t": "Résiliation et remboursement",
    "q7_p": "L'abonnement passe par l'App Store. Il se résilie à tout moment dans les réglages de votre compte Apple ; les remboursements sont traités par Apple sur reportaproblem.apple.com.",
    "help_p": "L'app a sa propre aide avec quatorze sujets courts : sur Mac sous Aide → Aide AutoPress (⌘?), sur iPhone et iPad derrière le point d'interrogation en haut de la liste.",
    "help_link_home": "Ce que fait AutoPress",
    "back": "Retour à l'accueil", "foot_support": "Assistance",
}

S["es"] = {
    "title": "Soporte · Hybrid AutoPress",
    "description": "Ayuda con Hybrid AutoPress: contacto, respuestas a los problemas de conexión más frecuentes y a la suscripción.",
    "nav_home": "Inicio", "eyebrow": "Soporte",
    "h1": "Soporte de Hybrid AutoPress",
    "lede": "¿Preguntas, problemas o sugerencias? Escríbeme; respondo yo mismo a cada mensaje. Muchos problemas de conexión tienen una solución rápida, más abajo.",
    "contact_h": "Contacto", "contact_p": "Envía un correo, en inglés o en alemán. Suelo responder en dos días laborables.",
    "include_h": "Lo que me ayuda a ayudarte",
    "include_1": "Tu dispositivo y la versión del sistema (iPhone, iPad o Mac; iOS, iPadOS o macOS).",
    "include_2": "La versión de la app: en el Mac en Hybrid AutoPress → Acerca de Hybrid AutoPress.",
    "include_3": "Tu versión de WordPress y tu proveedor de alojamiento, y los plugins de seguridad o SEO.",
    "include_4": "El mensaje exacto de la app y los pasos previos. Una captura de pantalla es bienvenida.",
    "faq_h": "Problemas frecuentes",
    "q1_t": "«La autenticación no llegó a WordPress.»",
    "q1_p": "El servidor web descarta la autenticación antes de que WordPress la vea; es habitual en alojamientos compartidos. Añade esta línea al archivo .htaccess de tu carpeta de WordPress y vuelve a conectar:",
    "q2_t": "«Las contraseñas de aplicación no están disponibles en este sitio.»",
    "q2_p": "Necesitan WordPress 5.6 o posterior y https. Los plugins de seguridad como Wordfence las desactivan por defecto; permítelas en los ajustes del plugin.",
    "q3_t": "«Se encontró WordPress, pero su API REST está desactivada o bloqueada.»",
    "q3_p": "Un plugin de seguridad o una regla del servidor bloquea /wp-json/. Debe ser accesible para usuarios conectados; revisa los ajustes de REST API del plugin o consulta a tu proveedor.",
    "q4_t": "«El nombre de usuario o la contraseña de aplicación son incorrectos.»",
    "q4_p": "Usa una contraseña de aplicación (Usuarios → Perfil → Contraseñas de aplicación), no tu contraseña normal. O elige iniciar sesión con el navegador y WordPress creará una por ti.",
    "q5_t": "Una imagen es mayor de lo que acepta el sitio",
    "q5_p": "Elige un lado largo menor en los ajustes de imagen (fila Imágenes de la lista, en el Mac ⌘,) o aumenta el límite de subida en tu proveedor.",
    "q6_t": "Restaurar o gestionar AutoPress Pro",
    "q6_p": "Abre la ventana Pro y elige «Restaurar compras» en un dispositivo nuevo con el mismo Apple Account, o «Gestionar suscripción» para cambiarla o cancelarla.",
    "q7_t": "Cancelación y reembolsos",
    "q7_p": "La suscripción va por el App Store. Se cancela cuando quieras en los ajustes de tu Apple Account; los reembolsos los gestiona Apple en reportaproblem.apple.com.",
    "help_p": "La app tiene su propia ayuda con catorce temas breves: en el Mac en Ayuda → Ayuda de AutoPress (⌘?), en iPhone y iPad tras el signo de interrogación arriba en la lista.",
    "help_link_home": "Lo que hace AutoPress",
    "back": "Volver al inicio", "foot_support": "Soporte",
}

S["it"] = {
    "title": "Supporto · Hybrid AutoPress",
    "description": "Aiuto per Hybrid AutoPress: contatto, risposte ai problemi di collegamento più comuni e all'abbonamento.",
    "nav_home": "Home", "eyebrow": "Supporto",
    "h1": "Supporto per Hybrid AutoPress",
    "lede": "Domande, problemi o suggerimenti? Scrivimi; rispondo di persona a ogni messaggio. Molti problemi di collegamento si risolvono in fretta, vedi sotto.",
    "contact_h": "Contatto", "contact_p": "Manda un'e-mail, in inglese o in tedesco. Di solito rispondo entro due giorni lavorativi.",
    "include_h": "Cosa mi aiuta ad aiutarti",
    "include_1": "Il tuo dispositivo e la versione del sistema (iPhone, iPad o Mac; iOS, iPadOS o macOS).",
    "include_2": "La versione dell'app: sul Mac in Hybrid AutoPress → Informazioni su Hybrid AutoPress.",
    "include_3": "La tua versione di WordPress e il tuo provider, e gli eventuali plugin di sicurezza o SEO.",
    "include_4": "Il messaggio esatto dell'app e i passaggi che lo hanno preceduto. Uno screenshot è benvenuto.",
    "faq_h": "Problemi comuni",
    "q1_t": "“L'autenticazione non è arrivata a WordPress.”",
    "q1_p": "Il server web scarta l'autenticazione prima che WordPress la veda; succede spesso con l'hosting condiviso. Aggiungi questa riga al file .htaccess nella cartella di WordPress e collegati di nuovo:",
    "q2_t": "“Le password applicazione non sono disponibili su questo sito.”",
    "q2_p": "Richiedono WordPress 5.6 o successivo e https. Plugin di sicurezza come Wordfence le disattivano per impostazione predefinita; consentile nelle impostazioni del plugin.",
    "q3_t": "“WordPress è stato trovato, ma la sua API REST è disattivata o bloccata.”",
    "q3_p": "Un plugin di sicurezza o una regola del server blocca /wp-json/. Deve essere raggiungibile per gli utenti connessi; controlla le impostazioni REST API del plugin o chiedi al tuo provider.",
    "q4_t": "“Nome utente o password applicazione errati.”",
    "q4_p": "Usa una password applicazione (Utenti → Profilo → Password applicazione), non la tua password di accesso. Oppure scegli l'accesso dal browser e WordPress ne crea una per te.",
    "q5_t": "Un'immagine è più grande di quanto il sito accetta",
    "q5_p": "Scegli un lato lungo più piccolo nelle impostazioni delle immagini (riga Immagini dell'elenco, sul Mac ⌘,) o aumenta il limite di caricamento presso il tuo provider.",
    "q6_t": "Ripristinare o gestire AutoPress Pro",
    "q6_p": "Apri la finestra Pro e scegli “Ripristina acquisti” su un nuovo dispositivo con lo stesso Apple Account, oppure “Gestisci abbonamento” per modificarlo o disdirlo.",
    "q7_t": "Disdetta e rimborsi",
    "q7_p": "L'abbonamento passa dall'App Store. Si disdice in qualsiasi momento nelle impostazioni del tuo Apple Account; i rimborsi li gestisce Apple su reportaproblem.apple.com.",
    "help_p": "L'app ha un proprio aiuto con quattordici argomenti brevi: sul Mac in Aiuto → Aiuto AutoPress (⌘?), su iPhone e iPad dietro il punto interrogativo in cima all'elenco.",
    "help_link_home": "Cosa fa AutoPress",
    "back": "Torna alla home", "foot_support": "Supporto",
}

S["pt"] = {
    "title": "Suporte · Hybrid AutoPress",
    "description": "Ajuda com o Hybrid AutoPress: contacto, respostas aos problemas de ligação mais comuns e à subscrição.",
    "nav_home": "Início", "eyebrow": "Suporte",
    "h1": "Suporte do Hybrid AutoPress",
    "lede": "Perguntas, problemas ou sugestões? Escreva-me; respondo pessoalmente a cada mensagem. Muitos problemas de ligação resolvem-se depressa, veja abaixo.",
    "contact_h": "Contacto", "contact_p": "Envie um e-mail, em inglês ou em alemão. Normalmente respondo em dois dias úteis.",
    "include_h": "O que me ajuda a ajudar",
    "include_1": "O seu dispositivo e a versão do sistema (iPhone, iPad ou Mac; iOS, iPadOS ou macOS).",
    "include_2": "A versão da app: no Mac em Hybrid AutoPress → Acerca do Hybrid AutoPress.",
    "include_3": "A sua versão do WordPress e o seu alojamento, e plugins de segurança ou SEO.",
    "include_4": "A mensagem exata da app e os passos anteriores. Uma captura de ecrã é bem-vinda.",
    "faq_h": "Problemas comuns",
    "q1_t": "«A autenticação não chegou ao WordPress.»",
    "q1_p": "O servidor web descarta a autenticação antes de o WordPress a ver; é comum em alojamento partilhado. Acrescente esta linha ao ficheiro .htaccess na pasta do WordPress e volte a ligar:",
    "q2_t": "«As palavras-passe de aplicação não estão disponíveis neste site.»",
    "q2_p": "Precisam do WordPress 5.6 ou posterior e de https. Plugins de segurança como o Wordfence desativam-nas por predefinição; permita-as nas definições do plugin.",
    "q3_t": "«O WordPress foi encontrado, mas a sua API REST está desativada ou bloqueada.»",
    "q3_p": "Um plugin de segurança ou uma regra do servidor bloqueia /wp-json/. Tem de estar acessível a utilizadores com sessão iniciada; verifique as definições REST API do plugin ou pergunte ao seu alojamento.",
    "q4_t": "«O nome de utilizador ou a palavra-passe de aplicação estão errados.»",
    "q4_p": "Use uma palavra-passe de aplicação (Utilizadores → Perfil → Palavras-passe de aplicação), não a sua palavra-passe normal. Ou escolha iniciar sessão pelo browser e o WordPress cria uma por si.",
    "q5_t": "Uma imagem é maior do que o site aceita",
    "q5_p": "Escolha um lado maior mais pequeno nas definições de imagem (linha Imagens da lista, no Mac ⌘,) ou aumente o limite de envio no seu alojamento.",
    "q6_t": "Restaurar ou gerir o AutoPress Pro",
    "q6_p": "Abra a janela Pro e escolha «Restaurar compras» num dispositivo novo com a mesma Apple Account, ou «Gerir subscrição» para a alterar ou cancelar.",
    "q7_t": "Cancelamento e reembolsos",
    "q7_p": "A subscrição passa pela App Store. Cancela-se a qualquer momento nas definições da sua Apple Account; os reembolsos são tratados pela Apple em reportaproblem.apple.com.",
    "help_p": "A app tem a sua própria ajuda com catorze temas curtos: no Mac em Ajuda → Ajuda do AutoPress (⌘?), no iPhone e iPad atrás do ponto de interrogação no topo da lista.",
    "help_link_home": "O que o AutoPress faz",
    "back": "Voltar ao início", "foot_support": "Suporte",
}

S["nl"] = {
    "title": "Ondersteuning · Hybrid AutoPress",
    "description": "Hulp bij Hybrid AutoPress: contact, antwoorden op de meest voorkomende verbindingsproblemen en over het abonnement.",
    "nav_home": "Home", "eyebrow": "Ondersteuning",
    "h1": "Ondersteuning voor Hybrid AutoPress",
    "lede": "Vragen, problemen of wensen? Schrijf me; ik beantwoord elk bericht zelf. Veel verbindingsproblemen zijn snel opgelost, zie hieronder.",
    "contact_h": "Contact", "contact_p": "Stuur een e-mail, in het Engels of Duits. Meestal antwoord ik binnen twee werkdagen.",
    "include_h": "Wat me helpt om te helpen",
    "include_1": "Je apparaat en de systeemversie (iPhone, iPad of Mac; iOS, iPadOS of macOS).",
    "include_2": "De appversie: op de Mac onder Hybrid AutoPress → Over Hybrid AutoPress.",
    "include_3": "Je WordPress-versie en je hostingprovider, en eventuele beveiligings- of SEO-plug-ins.",
    "include_4": "De precieze melding van de app en de stappen ervoor. Een schermafbeelding is welkom.",
    "faq_h": "Veelvoorkomende problemen",
    "q1_t": "‘De aanmelding is niet bij WordPress aangekomen.’",
    "q1_p": "De webserver laat de aanmelding vallen voordat WordPress haar ziet; dat is gebruikelijk bij shared hosting. Voeg deze regel toe aan het .htaccess-bestand in je WordPress-map en verbind opnieuw:",
    "q2_t": "‘Applicatiewachtwoorden zijn op deze website niet beschikbaar.’",
    "q2_p": "Ze vereisen WordPress 5.6 of nieuwer en https. Beveiligingsplug-ins zoals Wordfence schakelen ze standaard uit; sta ze toe in de instellingen van de plug-in.",
    "q3_t": "‘WordPress is gevonden, maar de REST-API is uitgeschakeld of geblokkeerd.’",
    "q3_p": "Een beveiligingsplug-in of serverregel blokkeert /wp-json/. Het moet bereikbaar zijn voor ingelogde gebruikers; controleer de REST-API-instellingen van de plug-in of vraag het je provider.",
    "q4_t": "‘Gebruikersnaam of applicatiewachtwoord is onjuist.’",
    "q4_p": "Gebruik een applicatiewachtwoord (Gebruikers → Profiel → Applicatiewachtwoorden), niet je gewone inlogwachtwoord. Of kies inloggen via de browser, dan maakt WordPress er een voor je aan.",
    "q5_t": "Een afbeelding is groter dan de website accepteert",
    "q5_p": "Kies een kleinere lange zijde in de afbeeldingsinstellingen (regel Afbeeldingen in de lijst, op de Mac ⌘,) of verhoog de uploadlimiet bij je provider.",
    "q6_t": "AutoPress Pro herstellen of beheren",
    "q6_p": "Open het Pro-venster en kies ‘Herstel aankopen’ op een nieuw apparaat met hetzelfde Apple Account, of ‘Beheer abonnement’ om het te wijzigen of op te zeggen.",
    "q7_t": "Opzeggen en terugbetaling",
    "q7_p": "Het abonnement loopt via de App Store. Het is altijd op te zeggen in de instellingen van je Apple Account; terugbetalingen handelt Apple af via reportaproblem.apple.com.",
    "help_p": "De app heeft een eigen help met veertien korte onderwerpen: op de Mac onder Help → AutoPress Help (⌘?), op iPhone en iPad achter het vraagteken bovenaan de lijst.",
    "help_link_home": "Wat AutoPress doet",
    "back": "Terug naar de startpagina", "foot_support": "Ondersteuning",
}

S["ja"] = {
    "title": "サポート · Hybrid AutoPress",
    "description": "Hybrid AutoPress のサポート：お問い合わせ、よくある接続の問題への回答、サブスクリプションについて。",
    "nav_home": "ホーム", "eyebrow": "サポート",
    "h1": "Hybrid AutoPress サポート",
    "lede": "ご質問、問題、ご要望はメールでどうぞ。すべてのメッセージに私自身がお答えします。接続の問題の多くはすぐに解決できます。下をご覧ください。",
    "contact_h": "お問い合わせ", "contact_p": "英語またはドイツ語でメールをお送りください。通常、2営業日以内にお返事します。",
    "include_h": "お問い合わせの際にあると助かるもの",
    "include_1": "お使いのデバイスとシステムのバージョン（iPhone、iPad、Mac／iOS、iPadOS、macOS）。",
    "include_2": "アプリのバージョン：Mac では Hybrid AutoPress →「Hybrid AutoPress について」。",
    "include_3": "WordPress のバージョンとホスティング事業者、セキュリティや SEO のプラグイン。",
    "include_4": "アプリが表示したメッセージそのままと、そこまでの手順。スクリーンショットも歓迎です。",
    "faq_h": "よくある問題",
    "q1_t": "「認証情報がWordPressに届きませんでした。」",
    "q1_p": "ウェブサーバーが WordPress に渡す前に認証情報を落としています。共用ホスティングでよくあります。WordPress フォルダの .htaccess ファイルに次の行を追加して、もう一度接続してください：",
    "q2_t": "「このウェブサイトではアプリケーションパスワードが利用できません。」",
    "q2_p": "WordPress 5.6 以降と https が必要です。Wordfence などのセキュリティプラグインは初期設定で無効にします。プラグインの設定で許可してください。",
    "q3_t": "「WordPressは見つかりましたが、REST APIが無効化またはブロックされています。」",
    "q3_p": "セキュリティプラグインかサーバーのルールが /wp-json/ をブロックしています。ログイン中のユーザーがアクセスできる必要があります。プラグインの REST API 設定を確認するか、ホスティング事業者にお問い合わせください。",
    "q4_t": "「ユーザー名またはアプリケーションパスワードが正しくありません。」",
    "q4_p": "通常のログインパスワードではなく、アプリケーションパスワード（ユーザー → プロフィール → アプリケーションパスワード）を使ってください。または「ブラウザでログイン」を選ぶと、WordPress が自動で作成します。",
    "q5_t": "画像がサイトの上限より大きい",
    "q5_p": "画像設定（リストの「画像」、Mac では ⌘,）で長辺を小さくするか、ホスティング事業者でアップロード上限を引き上げてください。",
    "q6_t": "AutoPress Pro の復元・管理",
    "q6_p": "Pro ウインドウを開き、同じ Apple Account の新しいデバイスでは「購入を復元」を、変更や解約には「サブスクリプションを管理」を選んでください。",
    "q7_t": "解約と返金",
    "q7_p": "サブスクリプションは App Store 経由です。Apple Account の設定でいつでも解約できます。返金は Apple が reportaproblem.apple.com で受け付けています。",
    "help_p": "アプリには14の短いトピックからなるヘルプがあります：Mac では ヘルプ →「AutoPress ヘルプ」（⌘?）、iPhone と iPad ではリスト上部の疑問符から。",
    "help_link_home": "AutoPress でできること",
    "back": "ホームに戻る", "foot_support": "サポート",
}

S["zh"] = {
    "title": "支持 · Hybrid AutoPress",
    "description": "Hybrid AutoPress 帮助：联系方式、最常见连接问题的解答以及订阅相关信息。",
    "nav_home": "首页", "eyebrow": "支持",
    "h1": "Hybrid AutoPress 支持",
    "lede": "有问题、遇到故障或有建议？请给我写信；每封邮件我都亲自回复。许多连接问题都能很快解决，见下文。",
    "contact_h": "联系", "contact_p": "请用英语或德语发送电子邮件。我通常在两个工作日内回复。",
    "include_h": "这些信息有助于我帮你",
    "include_1": "你的设备和系统版本（iPhone、iPad 或 Mac；iOS、iPadOS 或 macOS）。",
    "include_2": "App 版本：在 Mac 上见 Hybrid AutoPress →“关于 Hybrid AutoPress”。",
    "include_3": "你的 WordPress 版本和托管商，以及安全或 SEO 插件。",
    "include_4": "App 显示的确切信息，以及之前的操作步骤。欢迎附上截图。",
    "faq_h": "常见问题",
    "q1_t": "“登录信息未到达 WordPress。”",
    "q1_p": "Web 服务器在 WordPress 看到之前丢弃了登录信息；这在共享主机上很常见。请在 WordPress 文件夹的 .htaccess 文件中加入这一行，然后重新连接：",
    "q2_t": "“此网站不支持应用程序密码。”",
    "q2_p": "需要 WordPress 5.6 或更高版本以及 https。Wordfence 等安全插件默认会关闭它们；请在插件设置中允许。",
    "q3_t": "“找到了 WordPress，但其 REST API 已关闭或被阻止。”",
    "q3_p": "某个安全插件或服务器规则阻止了 /wp-json/。它必须对已登录用户可访问；请检查插件的 REST API 设置或咨询托管商。",
    "q4_t": "“用户名或应用程序密码错误。”",
    "q4_p": "请使用应用程序密码（用户 → 个人资料 → 应用程序密码），而不是普通登录密码。或者选择通过浏览器登录，WordPress 会为你创建一个。",
    "q5_t": "图片超过了网站接受的大小",
    "q5_p": "在图片设置中选择更小的长边（列表中的“图片”一行，Mac 上 ⌘,），或在托管商处提高上传限制。",
    "q6_t": "恢复或管理 AutoPress Pro",
    "q6_p": "打开 Pro 窗口，在使用同一 Apple 账户的新设备上选择“恢复购买”，或选择“管理订阅”来更改或取消。",
    "q7_t": "取消与退款",
    "q7_p": "订阅通过 App Store 进行。可随时在 Apple 账户设置中取消；退款由 Apple 在 reportaproblem.apple.com 处理。",
    "help_p": "App 自带帮助，共十四个简短主题：Mac 上见 帮助 →“AutoPress 帮助”（⌘?），iPhone 和 iPad 上点列表顶部的问号。",
    "help_link_home": "AutoPress 能做什么",
    "back": "返回首页", "foot_support": "支持",
}
