# The words of the page, per language. English is the master; every other
# language is a full dictionary of the same keys (build.py refuses a missing one).
# HTML is allowed in values; keep it to <span class="hl">, <code> and <br>.

T = {}

T["en"] = {
    "title": "Hybrid AutoPress: Markdown to WordPress, many files at once",
    "description": "Hybrid AutoPress uploads many Markdown files to WordPress in one go: as posts or pages, as drafts, published or scheduled, with images, categories and SEO fields. For iPhone, iPad and Mac.",
    "skip": "Skip to content",
    "lang_menu_label": "Language",
    "nav_how": "How it works", "nav_images": "Images", "nav_sites": "Your WordPress", "nav_pro": "Pro",

    "hero_eyebrow": "For iPhone, iPad and Mac",
    "hero_h1": 'A folder of Markdown in. <span class="hl">A WordPress site out.</span>',
    "hero_lede": "Hybrid AutoPress uploads many Markdown files to WordPress in one go. Every file becomes a post or a page, with headings, links, lists, tables and images, saved as a draft, published right away or scheduled for later.",
    "soon": "Coming soon to the App Store",
    "hero_more": "See how it works",
    "hero_alt": "Hybrid AutoPress on the Mac: seven Markdown documents in the list, the post “Lisbon in Three Days” with its featured image, credit, alt text, slug, excerpt and categories.",

    "step": "Step",
    "s1_h": "Add files. Or a whole folder.",
    "s1_p": "Pick single files, choose a folder including its subfolders, or drag everything into the window. AutoPress reads each title from the front matter, the first heading or the file name, and finds the featured image by itself.",
    "s1_alt": "The document list on the Mac with seven Markdown files, each marked as post or page.",
    "s2_h": "Decide once. Adjust where needed.",
    "s2_p": "Post or page; draft, publish now or schedule: set it once for all documents and override it for any single one. A whole batch can be staggered, the first one on a date, the rest a day apart. Before anything goes live at once, AutoPress asks once.",
    "s2_alt": "All documents set to Schedule, staggered one day apart, with the dates shown in the list.",
    "s3_h": "Press upload. Watch it go.",
    "s3_p": "One document after the other is created in WordPress, its pictures first. A progress bar shows how far along you are, and you can stop at any time; what is uploaded stays uploaded.",
    "s3_alt": "An upload in progress: three of seven documents are done, one is being created in WordPress, the rest are waiting.",
    "s4_h": "Done. With a link back.",
    "s4_p": "Every finished document gets a green check mark and a link to view it on the site or to keep editing in WordPress. If something fails, AutoPress tells you why and what to do about it, and sends the document again next time.",
    "s4_alt": "All seven documents carry a green check mark; the selected one offers “View” and “Edit in WordPress”.",

    "blk_eyebrow": "What arrives",
    "blk_h": 'Real blocks. <span class="hl">Not a blob.</span>',
    "blk_lede": "Your Markdown arrives as blocks of the WordPress block editor, not as one big unbreakable chunk. Every heading, paragraph, list, quote, table and image is its own block that can be edited, moved or deleted on its own.",
    "blk_1_t": "Every element, its own block", "blk_1_p": "Headings of every level, paragraphs with bold, italic, code and links, ordered and nested lists, task lists, quotes, code blocks and separators.",
    "blk_2_t": "Tables and images, the real thing", "blk_2_p": "A Markdown table becomes a table block with its alignment. A picture becomes an image block with alt text and caption; a linked picture keeps its link.",
    "blk_3_t": "Made for text from AI tools", "blk_3_p": "Markdown from ChatGPT, Claude and the like arrives as is. A stray ** on its own line, a common slip in generated text, is repaired quietly, as in Hybrid.",
    "d_heading": "Heading", "d_paragraph": "Paragraph", "d_image": "Image", "d_table": "Table", "d_list": "List", "d_quote": "Quote",

    "img_eyebrow": "Images",
    "img_h": 'Your pictures <span class="hl">come along.</span>',
    "img_lede": "No more uploading images by hand and patching links. What lies next to your Markdown file arrives in WordPress with it, at web size, cropped the way you want and with your name in the corner.",
    "img_1_t": "Into the media library", "img_1_p": "Local images in the text are uploaded with their alt text and linked in the post. Each one only once per site and session, however many documents use it.",
    "img_2_t": "Web size, JPEG or WebP", "img_2_p": "Scaled down before the upload, never up: 1200, 1600, 2000 or 2560 pixels on the long edge. HEIC photos from the iPhone are converted; transparency stays PNG.",
    "img_3_t": "Crop every picture", "img_3_p": "16:9, 3:2, 4:3, 1:1, 4:5, 2:3 or 9:16. Move the picture under the frame, zoom with two fingers, and the chosen part arrives in full size.",
    "img_4_t": "A credit in the corner", "img_4_p": "“© Name” set into the lower right corner of every uploaded picture, along the bottom or up the edge, in white or black, in the size you choose, with a live preview.",
    "img_5_t": "Featured image, found automatically", "img_5_p": "Named in the front matter, or a picture with the same name next to the file: lisbon.md → lisbon.jpg. Or pick a file or a photo yourself.",
    "img_alt": "The crop editor on the iPhone: a landscape picture with the credit “© Maria Santos” in the corner and the shapes Original, 16:9, 3:2, 4:3, 1:1 and 4:5 below.",

    "sch_eyebrow": "Scheduling",
    "sch_h": 'Upload today. <span class="hl">Go live all month.</span>',
    "sch_lede": "Fifty documents do not have to appear on one day. Upload them now and let WordPress publish them by itself, at the times you choose.",
    "sch_1_t": "Draft, now or scheduled", "sch_1_p": "Draft is the default and never shows anything. Publish now goes live as soon as it is uploaded. Schedule sets a date and time for each document.",
    "sch_2_t": "Stagger a whole batch", "sch_2_p": "“First one on” a date, “then every” hour, three hours, day, two days or week. Fifty documents become an editorial calendar; single dates can still be changed afterwards.",
    "sch_3_t": "Your time, your clock", "sch_3_p": "The time is the one your device shows, whatever time zone the website is set to. A future date in a file's front matter schedules it; a past one backdates it.",
    "sch_alt": "A document on the iPhone set to Scheduled with the field “Goes live on” and a date picker.",

    "meta_eyebrow": "Metadata and search engines",
    "meta_h": 'Everything the post needs. <span class="hl">Read from your site.</span>',
    "meta_lede": "Nothing is tailored to one particular installation. AutoPress asks every website what it has, and shows exactly that.",
    "meta_1_t": "Categories and tags from your site", "meta_1_p": "Chosen from the site's own list, most used first, with a search for sites with thousands of tags. New ones are typed in and created when the document is uploaded. One choice can be applied to all documents.",
    "meta_2_t": "SEO fields for the plugin you have", "meta_2_p": "SEO title, meta description and focus keyphrase for Yoast SEO, Rank Math, SEOPress and Jetpack, with counters for the room search results have. Set them in the app or in the front matter.",
    "meta_3_t": "Author, comments, sticky", "meta_3_p": "Permalink slug, excerpt, the author if your account may publish for others, whether comments are open, and whether the post stays at the top of the blog.",
    "meta_4_t": "The website's own fields", "meta_4_p": "Fields that plugins or the theme have opened to apps, a subtitle, a message for social networks, appear by themselves, explained in plain words.",
    "meta_alt": "The category picker on the Mac: the site's categories with their counts, the new category “Portugal” ticked, a search field on top.",

    "dev_eyebrow": "One app, three devices",
    "dev_h": 'At your desk. <span class="hl">Or on the sofa.</span>',
    "dev_lede": "The same app on iPhone, iPad and Mac, one purchase for all three. Upload from wherever your files are: iCloud Drive, the Files app or a folder on your Mac.",
    "ipad_alt": "Hybrid AutoPress on the iPad: all seven documents uploaded, the selected post saved as a draft.",
    "iphone_alt": "Hybrid AutoPress on the iPhone: the list of documents with the button “Upload 7 Documents”.",

    "fm_eyebrow": "Front matter",
    "fm_h": 'A few lines on top. <span class="hl">If you like.</span>',
    "fm_lede": "Optional front matter, as Jekyll, Hugo and Obsidian write it, controls everything per file. Without it, the first heading becomes the title and does not show up twice in the post. Everything in the file is only a starting value that can still be changed in the app.",
    "fm_1_t": "Everything WordPress needs", "fm_1_p": "title, type, status, date, slug, excerpt, tags, categories, author, comments, sticky, featured_image and its alt text.",
    "fm_2_t": "Pictures and search engines, too", "fm_2_p": "credit for the pictures of that document; seo_title, meta_description and focus_keyword for your SEO plugin.",
    "fm_3_t": "Straight from your writing tool", "fm_3_p": "Files from Hybrid, Obsidian, iA Writer or a static-site generator work as they are. AutoPress reads .md, .markdown, .mdown, .mkd and .mdwn.",
    "code_c1": "# optional: every line may be left out",
    "code_desc": "Seven hills, one tram line, the best custard tarts.",
    "code_body": "Lisbon rewards people who walk …",

    "site_eyebrow": "Your WordPress",
    "site_h": 'Works with your WordPress. <span class="hl">Wherever it is hosted.</span>',
    "site_lede": "Sign in through the browser and WordPress itself creates an application password for the app. Your login password never reaches AutoPress, and the access can be revoked in your profile at any time. WordPress.com sites connect the same way. Any WordPress 5.6 or later, reachable via https.",
    "hosts_more": "… and any other host",
    "c1_t": "Credentials stay in the keychain", "c1_p": "Never in the settings, never in a file. Websites are only ever contacted via https; over an unencrypted connection nothing is sent.",
    "c2_t": "Errors with a way out", "c2_p": "If your server swallows the sign-in, which is common with shared hosting, AutoPress recognises it and shows the <code>.htaccess</code> line that fixes it. A security plugin in the way is named.",
    "c3_t": "Talks to your site, nothing else", "c3_p": "No account needed, no tracking, no server in between. Documents and pictures go from your device straight to your WordPress.",
    "c4_t": "Help, built in", "c4_p": "Fourteen short topics from the first step to troubleshooting, in all nine languages, plus a hint wherever one is needed: under the fields, at sign-in, with every error.",

    "pro_eyebrow": "AutoPress Pro",
    "pro_h": 'Seven days free. <span class="hl">Then Pro, or free for good.</span>',
    "pro_lede": "After installation everything is usable for seven days, no account, no payment details. Then the AutoPress Pro subscription, monthly or yearly, keeps it that way; the App Store shows the price. Without it the app goes on as a free version.",
    "pro_free_h": "Free", "pro_pro_h": "AutoPress Pro",
    "pro_r1_free": "One document at a time", "pro_r1_pro": "Any number of documents at once",
    "pro_r2_free": "Pictures at full size, as JPEG", "pro_r2_pro": "Scaled to web size, JPEG or WebP",
    "pro_r3_free": "Draft or publish now", "pro_r3_pro": "Plus scheduled publishing, staggered for a batch",
    "pro_r4_free": "Post or page, featured image, crop, credit", "pro_r4_pro": "Plus details, options, SEO fields and the site's own fields",
    "pro_note": "Locked fields are not sent in the free version, not even when the Markdown file sets them; a scheduled document becomes a draft, never public by accident. The subscription runs through the App Store and can be cancelled there at any time.",
    "pro_alt": "The Pro window on the Mac: the five Pro features, the monthly and yearly plan, Restore Purchases and Manage Subscription.",

    "ben_eyebrow": "What you get out of it",
    "ben_h": 'Less clicking. <span class="hl">More publishing.</span>',
    "b1_t": "One click instead of twenty rounds", "b1_p": "Twenty articles no longer mean twenty times copy, paste, upload images, fix links, pick categories. Add the folder, press upload.",
    "b2_t": "Drafts first", "b2_p": "Everything can arrive as a draft. Check it in WordPress and publish when you are happy with it.",
    "b3_t": "Your text stays yours", "b3_p": "The Markdown files on your disk remain the original, readable in any editor, today and in ten years.",
    "b4_t": "Made for AI workflows", "b4_p": "Texts from ChatGPT, Claude and the like arrive as Markdown anyway. AutoPress takes them to your site without detours.",
    "b5_t": "For whole sites, too", "b5_p": "Moving a site or starting a new one? Pages and posts go up in a single run, tags, categories and pictures included.",
    "sis_t": "From the maker of Hybrid", "sis_p": "Hybrid is the Markdown editor that knows who wrote what: you, an AI or a source. Both use the same Markdown engine, so what you saw in Hybrid is what arrives in WordPress.",
    "sis_link": "Discover Hybrid",

    "lang_eyebrow": "Speaks your language",
    "lang_h": 'Nine languages. <span class="hl">In the app and on this page.</span>',
    "lang_p": "Hybrid AutoPress follows the language of your device, and the built-in help does too.",
    "end_h": 'Write in Markdown. <span class="hl">Publish in bulk.</span>',
    "end_lede": "Hybrid AutoPress is coming to the App Store: one app for iPhone, iPad and Mac.",
    "req": "Requires iOS 17, iPadOS 17 or macOS 14 · A WordPress site 5.6 or later, reachable via https",
    "foot_imprint": "Legal Notice (Impressum)", "foot_privacy": "Privacy Policy", "foot_app_privacy": "App Privacy", "foot_hybrid": "Hybrid Editor",
    "foot_hybrid_href": "https://hybrid-editor.com/",
    "fine": "WordPress is a trademark of the WordPress Foundation. Hybrid AutoPress is an independent app and is not affiliated with or endorsed by the WordPress Foundation, Automattic or any of the hosting companies or plugins named. Apple, iPhone, iPad, Mac and App Store are trademarks of Apple Inc. The screenshots show sample content.",
}

T["de"] = {
    "title": "Hybrid AutoPress: Markdown zu WordPress, viele Dateien auf einmal",
    "description": "Hybrid AutoPress lädt viele Markdown-Dateien auf einmal zu WordPress hoch: als Beiträge oder Seiten, als Entwurf, veröffentlicht oder geplant, mit Bildern, Kategorien und SEO-Feldern. Für iPhone, iPad und Mac.",
    "skip": "Zum Inhalt springen",
    "lang_menu_label": "Sprache",
    "nav_how": "So geht’s", "nav_images": "Bilder", "nav_sites": "Dein WordPress", "nav_pro": "Pro",

    "hero_eyebrow": "Für iPhone, iPad und Mac",
    "hero_h1": 'Ein Ordner Markdown rein. <span class="hl">Eine WordPress-Website raus.</span>',
    "hero_lede": "Hybrid AutoPress lädt viele Markdown-Dateien auf einmal zu WordPress hoch. Aus jeder Datei wird ein Beitrag oder eine Seite, mit Überschriften, Links, Listen, Tabellen und Bildern, als Entwurf gespeichert, sofort veröffentlicht oder für später geplant.",
    "soon": "Bald im App Store",
    "hero_more": "So funktioniert es",
    "hero_alt": "Hybrid AutoPress auf dem Mac: sieben Markdown-Dokumente in der Liste, der Beitrag „Lisbon in Three Days“ mit Beitragsbild, Bildnachweis, Alt-Text, Permalink, Auszug und Kategorien.",

    "step": "Schritt",
    "s1_h": "Dateien hinzufügen. Oder gleich den Ordner.",
    "s1_p": "Einzelne Dateien wählen, einen Ordner samt Unterordnern oder alles ins Fenster ziehen. Den Titel liest AutoPress aus dem Front Matter, der ersten Überschrift oder dem Dateinamen, und das Beitragsbild findet es von selbst.",
    "s1_alt": "Die Dokumentliste auf dem Mac mit sieben Markdown-Dateien, jede als Beitrag oder Seite markiert.",
    "s2_h": "Einmal entscheiden. Wo nötig abweichen.",
    "s2_p": "Beitrag oder Seite; Entwurf, sofort oder geplant: einmal für alle Dokumente einstellen und bei jedem einzelnen abweichen. Ein ganzer Stapel lässt sich staffeln, das erste an einem Datum, die übrigen im Tagesabstand. Bevor etwas sofort online geht, fragt AutoPress ein Mal nach.",
    "s2_alt": "Alle Dokumente auf „Planen“ gestellt, im Tagesabstand gestaffelt; die Liste zeigt die Termine.",
    "s3_h": "Hochladen. Und zusehen.",
    "s3_p": "Ein Dokument nach dem anderen entsteht in WordPress, die Bilder zuerst. Ein Fortschrittsbalken zeigt, wie weit du bist, und anhalten geht jederzeit; was hochgeladen ist, bleibt hochgeladen.",
    "s3_alt": "Ein laufender Upload: drei von sieben Dokumenten sind fertig, eines wird in WordPress angelegt, die übrigen warten.",
    "s4_h": "Fertig. Mit Link zurück.",
    "s4_p": "Jedes fertige Dokument bekommt einen grünen Haken und einen Link zur Ansicht auf der Website oder zum Weiterbearbeiten in WordPress. Geht etwas schief, sagt AutoPress, woran es liegt und was hilft, und sendet das Dokument beim nächsten Mal erneut.",
    "s4_alt": "Alle sieben Dokumente tragen einen grünen Haken; das ausgewählte bietet „View“ und „Edit in WordPress“.",

    "blk_eyebrow": "Was ankommt",
    "blk_h": 'Echte Blöcke. <span class="hl">Kein Klumpen.</span>',
    "blk_lede": "Dein Markdown kommt als Blöcke des WordPress-Block-Editors an, nicht als ein einziger, unteilbarer Brocken. Jede Überschrift, jeder Absatz, jede Liste, jedes Zitat, jede Tabelle und jedes Bild ist ein eigener Block, der sich für sich bearbeiten, verschieben oder löschen lässt.",
    "blk_1_t": "Jedes Element ein Block", "blk_1_p": "Überschriften aller Ebenen, Absätze mit fett, kursiv, Code und Links, nummerierte und verschachtelte Listen, Aufgabenlisten, Zitate, Code-Blöcke und Trenner.",
    "blk_2_t": "Tabellen und Bilder, richtig", "blk_2_p": "Eine Markdown-Tabelle wird zum Tabellen-Block samt Ausrichtung. Ein Bild wird zum Bild-Block mit Alt-Text und Beschriftung; ein verlinktes Bild behält seinen Link.",
    "blk_3_t": "Gemacht für Text aus KI-Werkzeugen", "blk_3_p": "Markdown aus ChatGPT, Claude und Co. kommt so an, wie es ist. Ein verirrtes ** allein auf einer Zeile, ein häufiger Fehler in generiertem Text, wird still repariert, wie in Hybrid.",
    "d_heading": "Überschrift", "d_paragraph": "Absatz", "d_image": "Bild", "d_table": "Tabelle", "d_list": "Liste", "d_quote": "Zitat",

    "img_eyebrow": "Bilder",
    "img_h": 'Deine Bilder <span class="hl">kommen mit.</span>',
    "img_lede": "Schluss mit Bildern von Hand hochladen und Links flicken. Was neben deiner Markdown-Datei liegt, kommt mit ihr in WordPress an, in Web-Größe, zugeschnitten, wie du willst, und mit deinem Namen in der Ecke.",
    "img_1_t": "Ab in die Mediathek", "img_1_p": "Lokale Bilder im Text werden mit ihrem Alt-Text hochgeladen und im Beitrag verknüpft. Jedes nur ein Mal pro Website und Sitzung, egal in wie vielen Dokumenten es vorkommt.",
    "img_2_t": "Web-Größe, JPEG oder WebP", "img_2_p": "Vor dem Hochladen verkleinert, nie vergrößert: 1200, 1600, 2000 oder 2560 Pixel an der langen Kante. HEIC-Fotos vom iPhone werden umgewandelt; Transparenz bleibt PNG.",
    "img_3_t": "Jedes Bild zuschneiden", "img_3_p": "16:9, 3:2, 4:3, 1:1, 4:5, 2:3 oder 9:16. Das Bild unter dem Rahmen verschieben, mit zwei Fingern zoomen, und der gewählte Ausschnitt kommt in voller Größe an.",
    "img_4_t": "Ein Bildnachweis in der Ecke", "img_4_p": "„© Name“ in der rechten unteren Ecke jedes hochgeladenen Bildes, entlang der Unterkante oder an der Seite nach oben, in Weiß oder Schwarz, in der Größe deiner Wahl, mit Live-Vorschau.",
    "img_5_t": "Beitragsbild, automatisch gefunden", "img_5_p": "Im Front Matter genannt oder ein gleichnamiges Bild neben der Datei: lissabon.md → lissabon.jpg. Oder du wählst selbst eine Datei oder ein Foto.",
    "img_alt": "Der Zuschnitt auf dem iPhone: ein Landschaftsbild mit dem Nachweis „© Maria Santos“ in der Ecke, darunter die Formate Original, 16:9, 3:2, 4:3, 1:1 und 4:5.",

    "sch_eyebrow": "Planung",
    "sch_h": 'Heute hochladen. <span class="hl">Den ganzen Monat erscheinen.</span>',
    "sch_lede": "Fünfzig Dokumente müssen nicht an einem Tag erscheinen. Lade sie jetzt hoch und lass WordPress sie von selbst veröffentlichen, zu den Zeiten, die du bestimmst.",
    "sch_1_t": "Entwurf, sofort oder geplant", "sch_1_p": "Entwurf ist der Standard und zeigt nie etwas. Sofort veröffentlichen geht online, sobald es hochgeladen ist. Planen setzt für jedes Dokument Datum und Uhrzeit.",
    "sch_2_t": "Einen ganzen Stapel staffeln", "sch_2_p": "„Das erste am“ Datum, „danach alle“ Stunde, drei Stunden, Tag, zwei Tage oder Woche. Aus fünfzig Dokumenten wird ein Redaktionsplan; einzelne Termine lassen sich danach noch ändern.",
    "sch_3_t": "Deine Zeit, deine Uhr", "sch_3_p": "Es gilt die Uhrzeit, die dein Gerät anzeigt, egal, auf welche Zeitzone die Website eingestellt ist. Ein künftiges Datum im Front Matter plant das Dokument; ein vergangenes datiert es zurück.",
    "sch_alt": "Ein Dokument auf dem iPhone mit Status „Scheduled“, dem Feld „Goes live on“ und einer Datumsauswahl.",

    "meta_eyebrow": "Metadaten und Suchmaschinen",
    "meta_h": 'Alles, was der Beitrag braucht. <span class="hl">Von deiner Website gelesen.</span>',
    "meta_lede": "Nichts ist auf eine bestimmte Installation zugeschnitten. AutoPress fragt jede Website, was sie hat, und zeigt genau das.",
    "meta_1_t": "Kategorien und Schlagwörter von deiner Website", "meta_1_p": "Aus der Liste der Website gewählt, die meistgenutzten zuerst, mit Suche für Websites mit Tausenden von Schlagwörtern. Neue werden eingetippt und beim Hochladen angelegt. Eine Auswahl lässt sich auf alle Dokumente übertragen.",
    "meta_2_t": "SEO-Felder für dein Plugin", "meta_2_p": "SEO-Titel, Meta-Beschreibung und Fokus-Keyphrase für Yoast SEO, Rank Math, SEOPress und Jetpack, mit Zählern für den Platz in den Suchergebnissen. In der App oder im Front Matter gesetzt.",
    "meta_3_t": "Autor, Kommentare, oben halten", "meta_3_p": "Permalink-Kürzel, Textauszug, der Autor, wenn dein Konto für andere veröffentlichen darf, ob Kommentare offen sind und ob der Beitrag oben im Blog bleibt.",
    "meta_4_t": "Die eigenen Felder der Website", "meta_4_p": "Felder, die Plugins oder das Theme für Apps geöffnet haben, ein Untertitel, eine Nachricht für soziale Netzwerke, erscheinen von selbst, verständlich erklärt.",
    "meta_alt": "Die Kategorienauswahl auf dem Mac: die Kategorien der Website mit ihren Zählern, die neue Kategorie „Portugal“ abgehakt, oben ein Suchfeld.",

    "dev_eyebrow": "Eine App, drei Geräte",
    "dev_h": 'Am Schreibtisch. <span class="hl">Oder auf dem Sofa.</span>',
    "dev_lede": "Dieselbe App auf iPhone, iPad und Mac, ein Kauf für alle drei. Lade von dort hoch, wo deine Dateien liegen: iCloud Drive, die Dateien-App oder ein Ordner auf dem Mac.",
    "ipad_alt": "Hybrid AutoPress auf dem iPad: alle sieben Dokumente hochgeladen, der ausgewählte Beitrag als Entwurf gesichert.",
    "iphone_alt": "Hybrid AutoPress auf dem iPhone: die Dokumentliste mit der Taste „Upload 7 Documents“.",

    "fm_eyebrow": "Front Matter",
    "fm_h": 'Ein paar Zeilen obendrauf. <span class="hl">Wenn du magst.</span>',
    "fm_lede": "Optionales Front Matter, wie Jekyll, Hugo und Obsidian es schreiben, steuert alles pro Datei. Ohne wird die erste Überschrift zum Titel und steht nicht doppelt im Beitrag. Alles in der Datei ist nur ein Startwert, der sich in der App noch ändern lässt.",
    "fm_1_t": "Alles, was WordPress braucht", "fm_1_p": "title, type, status, date, slug, excerpt, tags, categories, author, comments, sticky, featured_image und sein Alt-Text.",
    "fm_2_t": "Bilder und Suchmaschinen auch", "fm_2_p": "credit für die Bilder dieses Dokuments; seo_title, meta_description und focus_keyword für dein SEO-Plugin.",
    "fm_3_t": "Direkt aus deinem Schreibwerkzeug", "fm_3_p": "Dateien aus Hybrid, Obsidian, iA Writer oder einem Static-Site-Generator funktionieren, wie sie sind. AutoPress liest .md, .markdown, .mdown, .mkd und .mdwn.",
    "code_c1": "# optional: jede Zeile darf fehlen",
    "code_desc": "Seven hills, one tram line, the best custard tarts.",
    "code_body": "Lisbon rewards people who walk …",

    "site_eyebrow": "Dein WordPress",
    "site_h": 'Läuft mit deinem WordPress. <span class="hl">Egal, wo es gehostet ist.</span>',
    "site_lede": "Im Browser anmelden, und WordPress legt selbst ein Anwendungspasswort für die App an. Dein Login-Passwort erreicht AutoPress nie, und der Zugriff lässt sich jederzeit im Profil widerrufen. Websites bei WordPress.com verbindest du genauso. Jedes WordPress ab 5.6, erreichbar über https.",
    "hosts_more": "… und jeder andere Anbieter",
    "c1_t": "Zugangsdaten bleiben im Schlüsselbund", "c1_p": "Nie in den Einstellungen, nie in einer Datei. Websites werden nur über https angesprochen; über eine unverschlüsselte Verbindung wird nichts gesendet.",
    "c2_t": "Fehler mit Ausweg", "c2_p": "Verschluckt dein Server die Anmeldung, was bei Shared Hosting häufig vorkommt, erkennt AutoPress das und zeigt die <code>.htaccess</code>-Zeile, die es behebt. Ein Sicherheits-Plugin im Weg wird beim Namen genannt.",
    "c3_t": "Spricht mit deiner Website, sonst mit niemandem", "c3_p": "Kein Konto nötig, kein Tracking, kein Server dazwischen. Dokumente und Bilder gehen vom Gerät direkt zu deinem WordPress.",
    "c4_t": "Hilfe, eingebaut", "c4_p": "Vierzehn kurze Themen vom ersten Schritt bis zur Fehlersuche, in allen neun Sprachen, dazu ein Hinweis, wo einer gebraucht wird: unter den Feldern, beim Anmelden, bei jeder Fehlermeldung.",

    "pro_eyebrow": "AutoPress Pro",
    "pro_h": 'Sieben Tage kostenlos. <span class="hl">Dann Pro, oder für immer gratis.</span>',
    "pro_lede": "Nach der Installation ist sieben Tage lang alles nutzbar, ohne Konto, ohne Zahlungsdaten. Danach hält das Abo AutoPress Pro, monatlich oder jährlich, es dabei; den Preis zeigt der App Store. Ohne Abo läuft die App als kostenlose Version weiter.",
    "pro_free_h": "Kostenlos", "pro_pro_h": "AutoPress Pro",
    "pro_r1_free": "Ein Dokument zur Zeit", "pro_r1_pro": "Beliebig viele Dokumente auf einmal",
    "pro_r2_free": "Bilder in voller Größe, als JPEG", "pro_r2_pro": "Auf Web-Größe verkleinert, JPEG oder WebP",
    "pro_r3_free": "Entwurf oder sofort veröffentlichen", "pro_r3_pro": "Dazu geplante Veröffentlichung, gestaffelt für einen Stapel",
    "pro_r4_free": "Beitrag oder Seite, Beitragsbild, Zuschnitt, Bildnachweis", "pro_r4_pro": "Dazu Details, Optionen, SEO-Felder und die eigenen Felder der Website",
    "pro_note": "Gesperrte Felder werden in der kostenlosen Version nicht gesendet, auch dann nicht, wenn die Markdown-Datei sie setzt; ein geplantes Dokument wird zum Entwurf, nie versehentlich öffentlich. Das Abo läuft über den App Store und lässt sich dort jederzeit kündigen.",
    "pro_alt": "Das Pro-Fenster auf dem Mac: die fünf Pro-Funktionen, Monats- und Jahresabo, „Käufe wiederherstellen“ und „Abo verwalten“.",

    "ben_eyebrow": "Was du davon hast",
    "ben_h": 'Weniger klicken. <span class="hl">Mehr veröffentlichen.</span>',
    "b1_t": "Ein Klick statt zwanzig Runden", "b1_p": "Zwanzig Artikel heißen nicht mehr zwanzigmal kopieren, einfügen, Bilder hochladen, Links reparieren, Kategorien wählen. Ordner hinzufügen, hochladen.",
    "b2_t": "Erst mal als Entwurf", "b2_p": "Alles kann als Entwurf ankommen. In WordPress prüfen und veröffentlichen, wenn es passt.",
    "b3_t": "Dein Text bleibt deiner", "b3_p": "Die Markdown-Dateien auf deiner Festplatte bleiben das Original, lesbar in jedem Editor, heute und in zehn Jahren.",
    "b4_t": "Gemacht für KI-Workflows", "b4_p": "Texte aus ChatGPT, Claude und Co. kommen ohnehin als Markdown. AutoPress bringt sie ohne Umwege auf deine Website.",
    "b5_t": "Auch für ganze Websites", "b5_p": "Umzug oder Neustart? Seiten und Beiträge gehen in einem Durchgang hoch, samt Schlagwörtern, Kategorien und Bildern.",
    "sis_t": "Vom Macher von Hybrid", "sis_p": "Hybrid ist der Markdown-Editor, der weiß, wer was geschrieben hat: du, eine KI oder eine Quelle. Beide nutzen dieselbe Markdown-Umwandlung, was du in Hybrid gesehen hast, kommt so in WordPress an.",
    "sis_link": "Hybrid entdecken",

    "lang_eyebrow": "Spricht deine Sprache",
    "lang_h": 'Neun Sprachen. <span class="hl">In der App und auf dieser Seite.</span>',
    "lang_p": "Hybrid AutoPress folgt der Sprache deines Geräts, und die eingebaute Hilfe auch.",
    "end_h": 'In Markdown schreiben. <span class="hl">Im Stapel veröffentlichen.</span>',
    "end_lede": "Hybrid AutoPress kommt in den App Store: eine App für iPhone, iPad und Mac.",
    "req": "Benötigt iOS 17, iPadOS 17 oder macOS 14 · Eine WordPress-Website ab 5.6, erreichbar über https",
    "foot_imprint": "Impressum", "foot_privacy": "Datenschutz", "foot_app_privacy": "Datenschutz in der App", "foot_hybrid": "Hybrid Editor",
    "foot_hybrid_href": "https://hybrid-editor.com/de/",
    "fine": "WordPress ist eine Marke der WordPress Foundation. Hybrid AutoPress ist eine unabhängige App und steht in keiner Verbindung zur WordPress Foundation, zu Automattic oder zu den genannten Hosting-Anbietern und Plugins. Apple, iPhone, iPad, Mac und App Store sind Marken von Apple Inc. Die Screenshots zeigen Beispielinhalte; die Oberfläche der App gibt es in allen neun Sprachen.",
}

# The other languages live in lang/<code>.py, one file each.
import importlib as _importlib
for _code in ("fr", "es", "it", "pt", "nl", "ja", "zh"):
    try:
        T[_code] = _importlib.import_module(f"lang.{_code}").T
    except ModuleNotFoundError:
        pass
